server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  data:
    mongodb:
      uri: mongodb+srv://jlodarsantamaria_db_user:nT0dlTcHLqCVvV6p@clusterodar.topeczm.mongodb.net/active?appName=clusterodar
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/bank-nttdata/payment
  application:
    name: payment

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${localhost:${random.value}}
    service-url:
      default-zone: https://bnttdata-eureka-server.azurewebsites.net/eureka
    prefer-ip-address: true

springdoc:
  packagesToScan: com.nttdata.bootcamp

resilience4j.circuitbreaker:
  instances:
    payment:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 2s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10